name: terraform

on: [pull_request]

  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    name: terraform fmt
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ./

  tf-plan:
    runs-on: ubuntu-latest
    name: terraform plan
    needs: fmt-check

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform plan
        uses: dflook/terraform-plan@v1

